name: Grep TODO

on:
  push:
    branches:
      - ci-update  # Change this to the branch you want to trigger the workflow on

jobs:
  grep_todo_job:
    name: Grep TODO Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for TODO statements
        run: (find . -iname "*.cs" -exec grep -qi "todo" {} \; -print) > ./todo_log.txt


      - name: Check for Apache Licnse headers
        run: (find . \( -path "./git*" -o -name "README.md" \) -prune -o -type f -iname "*.cs" -exec grep -L "Apache License" {} \;) > ./license_log.txt

      - name: Save logs directory
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: todologs  # Specify the name for your artifact
          path: ./**/todo_log.txt  # Replace with the actual path to your generated JSON file

      - name: Save logs directory
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: licenselogs  # Specify the name for your artifact
          path: ./**/license_log.txt  # Replace with the actual path to your generated JSON file



