name: Run bash program

on:
  push:
    branches:
      - main

jobs:
  run-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run bash program
        run: |
          (for f in `find . -iname "*.java" -o -iname "*.cs" -o -iname "*.go"`; do grep -li todo $f; done) 

