name: Grep TODO

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  grep_todo_job:
    name: Grep TODO Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run grep command
        run: |
          for f in $(find . -iname "*.java" -o -iname "*.cs" -o -iname "*.go"); do
            grep -li "todo" $f
          done
