name: Run bash program

on:
  push:
    branches:
      - main

jobs:
  run-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run bash program
        run: |
          (for f in `find . -iname "*.java" -o -iname "*.cs" -o -iname "*.go"`; do grep -li todo $f; done) > todo.tmp.txt
          grep -q . todo.tmp.txt && echo "The following files contain todo" && cat todo.tmp.txt
          (for f in `find . -iname "*.java" -o -iname "*.cs" -o -iname "*.go"`;do grep -L Apache\ License $f; done | grep -v "AssemblyAttributes" | grep -v "AssemblyInfo") > license.tmp.txt
          grep -q . license.tmp.txt && echo "The following files are missing Apache License" && cat license.tmp.txt
