name: Grep TODO

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  grep_todo_job:
    name: Grep TODO Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for TODO statements
        run: |
          for f in $(find . -iname "*.java" -o -iname "*.cs" -o -iname "*.go"); do
            if grep -qi "todo" "$f"; then
              echo "TODO found in $f"
            fi
          done

      - name: Check for Apache Licnse headers
        run: |
          for f in $(find . -iname "*.java" -o -iname "*.cs" -o -iname "*.go"); do
            if grep -L "Apache\ License" "$f"; then
              echo "Apache License headers missing from $f"
            fi
          done
